### PR TITLE
(Update) Adopt PHP PSR-2 Coding Style 

### PR DESCRIPTION
**Pull request by HDVinnie**
- automated by php-shift
- untested

### CODE REVIEW

**Comment by Empornium** [comment]
We have our own style which we are developing and following, part of that style is K&R braces.

**Comment by HDVinnie** [comment]
Im confused because 1TBS is what your using now.....

My PR makes use of K&R style (PSR-2)

**Comment by Empornium** [comment]
We took a vote and most of our developers prefer this style. We use it consistently throughout our new code, that's not a mistake. Legacy code inherited from Gazelle is left as is and will be refactored as it's converted to Luminance code.

**Comment by HDVinnie** [comment]
Ok well just so your clear your using 1TBS and not K&R (like you said). Anyway good luck with the project.

**Pull request closed without merging**
